var searchData=
[
  ['language_0',['M*LIB: Generic type-safe Container Library for C language',['../index.html',1,'']]],
  ['len_20const_20char_20str2_20tt_1',['&lt;tt&gt;void string_replace_at (string_t v, size_t pos, size_t len, const char str2[])&lt;/tt&gt;',['../index.html#autotoc_md574',1,'']]],
  ['len_20tt_2',['&lt;tt&gt;M_MID_ARGS(first, len,...)&lt;/tt&gt;',['../index.html#autotoc_md657',1,'']]],
  ['length_20tt_3',['length tt',['../index.html#autotoc_md707',1,'&lt;tt&gt;size_t m_core_hash (const void *str, size_t length)&lt;/tt&gt;'],['../index.html#autotoc_md539',1,'&lt;tt&gt;void string_set_n(string_t v, const string_t ref, size_t offset, size_t length)&lt;/tt&gt;']]],
  ['lib_3a_20generic_20type_20safe_20container_20library_20for_20c_20language_4',['M*LIB: Generic type-safe Container Library for C language',['../index.html',1,'']]],
  ['lib_5fext_5fstruct_5',['lib_ext_struct',['../structlib__ext__struct.html',1,'']]],
  ['library_6',['Atomic library',['../md_include_2mutekix_2mlib_2doc_2DEV.html#autotoc_md2',1,'']]],
  ['library_20for_20c_20language_7',['M*LIB: Generic type-safe Container Library for C language',['../index.html',1,'']]],
  ['license_8',['License',['../index.html#autotoc_md917',1,'']]],
  ['like_9',['like',['../index.html#autotoc_md78',1,'&lt;tt&gt;const type_t *name_cget(const name_t container, const type_t key)&lt;/tt&gt; [for set-like]'],['../index.html#autotoc_md76',1,'&lt;tt&gt;const type_t *name_cget(const name_t container, size_t key)&lt;/tt&gt; [for sequence-like]'],['../index.html#autotoc_md77',1,'&lt;tt&gt;type_t *name_get(const name_t container, const type_t key)&lt;/tt&gt; [for set-like]'],['../index.html#autotoc_md75',1,'&lt;tt&gt;type_t *name_get(const name_t container, size_t key)&lt;/tt&gt; [for sequence-like]'],['../index.html#autotoc_md81',1,'&lt;tt&gt;type_t *name_get_emplace[suffix](const name_t container, args...)&lt;/tt&gt; [for set-like]']]],
  ['limb_20tt_10',['limb tt',['../index.html#autotoc_md705',1,'&lt;tt&gt;unsigned int m_core_clz32(uint32_t limb)&lt;/tt&gt;'],['../index.html#autotoc_md706',1,'&lt;tt&gt;unsigned int m_core_clz64(uint64_t limb)&lt;/tt&gt;']]],
  ['list_11',['list',['../index.html#autotoc_md437',1,'M-I-LIST'],['../index.html#autotoc_md115',1,'M-LIST'],['../index.html#autotoc_md13',1,'Singly List']]],
  ['list_20const_20type_20obj_20tt_12',['list const type obj tt',['../index.html#autotoc_md453',1,'&lt;tt&gt;type *name_next_obj(const name_t list, const type *obj)&lt;/tt&gt;'],['../index.html#autotoc_md454',1,'&lt;tt&gt;type *name_previous_obj(const name_t list, const type *obj)&lt;/tt&gt;']]],
  ['list_20index_20tt_13',['&lt;tt&gt;M_GET_AT(list, index)&lt;/tt&gt;',['../index.html#autotoc_md654',1,'']]],
  ['list_20name_5fit_5ft_20it_20type_20x_20tt_14',['&lt;tt&gt;void name_insert(name_t list, name_it_t it, type x)&lt;/tt&gt;',['../index.html#autotoc_md455',1,'']]],
  ['list_20of_20automatically_20tested_20systems_15',['List of automatically tested systems',['../md_include_2mutekix_2mlib_2doc_2DEV.html#autotoc_md0',1,'']]],
  ['list_20of_20manually_20tested_20systems_16',['List of manually tested systems',['../md_include_2mutekix_2mlib_2doc_2DEV.html#autotoc_md1',1,'']]],
  ['list_20tt_17',['list tt',['../index.html#autotoc_md450',1,'&lt;tt&gt;type *name_pop_back(name_t list)&lt;/tt&gt;'],['../index.html#autotoc_md451',1,'&lt;tt&gt;type *name_pop_front(name_t list)&lt;/tt&gt;'],['../index.html#autotoc_md128',1,'&lt;tt&gt;void name_reverse(name_t list)&lt;/tt&gt;'],['../index.html#autotoc_md139',1,'&lt;tt&gt;void name_reverse(name_t list)&lt;/tt&gt;']]],
  ['list_20type_20obj_20tt_18',['list type obj tt',['../index.html#autotoc_md447',1,'&lt;tt&gt;void name_push_back(name_t list, type *obj)&lt;/tt&gt;'],['../index.html#autotoc_md448',1,'&lt;tt&gt;void name_push_front(name_t list, type *obj)&lt;/tt&gt;']]],
  ['list1_20name_5fit_5ft_20it1_20name_5ft_20list2_20name_5fit_5ft_20it2_20tt_19',['&lt;tt&gt;void name_splice_at(name_t list1, name_it_t it1, name_t list2, name_it_t it2)&lt;/tt&gt;',['../index.html#autotoc_md126',1,'']]],
  ['list1_20name_5ft_20list2_20name_5fit_5ft_20it_20tt_20',['list1 name_t list2 name_it_t it tt',['../index.html#autotoc_md137',1,'&lt;tt&gt;void name_splice_back(name_t list1, name_t list2, name_it_t it)&lt;/tt&gt;'],['../index.html#autotoc_md125',1,'&lt;tt&gt;void name_splice_back(name_t list1, name_t list2, name_it_t it)&lt;/tt&gt;'],['../index.html#autotoc_md456',1,'&lt;tt&gt;void name_splice_back(name_t list1, name_t list2, name_it_t it)&lt;/tt&gt;']]],
  ['list1_20name_5ft_20list2_20tt_21',['list1 name_t list2 tt',['../index.html#autotoc_md138',1,'&lt;tt&gt;void name_splice(name_t list1, name_t list2)&lt;/tt&gt;'],['../index.html#autotoc_md127',1,'&lt;tt&gt;void name_splice(name_t list1, name_t list2)&lt;/tt&gt;'],['../index.html#autotoc_md457',1,'&lt;tt&gt;void name_splice(name_t list1, name_t list2)&lt;/tt&gt;']]],
  ['list2_20name_5fit_5ft_20it_20tt_22',['list2 name_it_t it tt',['../index.html#autotoc_md125',1,'&lt;tt&gt;void name_splice_back(name_t list1, name_t list2, name_it_t it)&lt;/tt&gt;'],['../index.html#autotoc_md137',1,'&lt;tt&gt;void name_splice_back(name_t list1, name_t list2, name_it_t it)&lt;/tt&gt;'],['../index.html#autotoc_md456',1,'&lt;tt&gt;void name_splice_back(name_t list1, name_t list2, name_it_t it)&lt;/tt&gt;']]],
  ['list2_20name_5fit_5ft_20it2_20tt_23',['&lt;tt&gt;void name_splice_at(name_t list1, name_it_t it1, name_t list2, name_it_t it2)&lt;/tt&gt;',['../index.html#autotoc_md126',1,'']]],
  ['list2_20tt_24',['list2 tt',['../index.html#autotoc_md138',1,'&lt;tt&gt;void name_splice(name_t list1, name_t list2)&lt;/tt&gt;'],['../index.html#autotoc_md127',1,'&lt;tt&gt;void name_splice(name_t list1, name_t list2)&lt;/tt&gt;'],['../index.html#autotoc_md457',1,'&lt;tt&gt;void name_splice(name_t list1, name_t list2)&lt;/tt&gt;']]],
  ['list_5fdef_20name_20type_20oplist_20tt_25',['&lt;tt&gt;LIST_DEF(name, type [, oplist])&lt;/tt&gt;',['../index.html#autotoc_md116',1,'']]],
  ['list_5fdef_5fas_20name_20name_5ft_20name_5fit_5ft_20type_20oplist_20tt_26',['&lt;tt&gt;LIST_DEF_AS(name, name_t, name_it_t, type [, oplist])&lt;/tt&gt;',['../index.html#autotoc_md117',1,'']]],
  ['list_5fdual_5fpush_5fdef_20name_20type_20oplist_20tt_27',['&lt;tt&gt;LIST_DUAL_PUSH_DEF(name, type[, oplist])&lt;/tt&gt;',['../index.html#autotoc_md129',1,'']]],
  ['list_5fdual_5fpush_5fdef_5fas_20name_20name_5ft_20name_5fit_5ft_20type_20oplist_20tt_28',['&lt;tt&gt;LIST_DUAL_PUSH_DEF_AS(name, name_t, name_it_t, type [, oplist])&lt;/tt&gt;',['../index.html#autotoc_md130',1,'']]],
  ['list_5fdual_5fpush_5finit_5fvalue_20tt_29',['&lt;tt&gt;LIST_DUAL_PUSH_INIT_VALUE()&lt;/tt&gt;',['../index.html#autotoc_md131',1,'']]],
  ['list_5finit_5fvalue_20tt_30',['&lt;tt&gt;LIST_INIT_VALUE()&lt;/tt&gt;',['../index.html#autotoc_md119',1,'']]],
  ['list_5foplist_20name_20oplist_20tt_31',['&lt;tt&gt;LIST_OPLIST(name [, oplist])&lt;/tt&gt;',['../index.html#autotoc_md118',1,'']]],
  ['lock_20tt_32',['&lt;tt&gt;void name_lock(name_t tree, bool lock)&lt;/tt&gt;',['../index.html#autotoc_md266',1,'']]],
  ['lsquo_20m_5fret_5farg_20n_20rsquo_20arglist_33',['&amp;lsquo;M_RET_ARG&apos;N&amp;rsquo;(arglist...)`',['../index.html#autotoc_md653',1,'']]]
];
